nav:
    - InspIRCd 3:
        - Installation: 3/installation/index.md
        - Configuration: 3/configuration/index.md
        - Commands: 3/commands/index.md
        - Modes: 3/modes.md
        - Modules: 3/modules/index.md
        - SNOMasks: 3/snomasks.md
        - Change Log: 3/change-log.md
    - Downloads: https://github.com/inspircd/inspircd/releases/latest
    - Issue Tracker: https://github.com/inspircd/inspircd/issues
    - Developer API: https://www.inspircd.org/api/
markdown_extensions:
    - admonition
    - extra
    - markdown_include.include:
          base_path: docs
plugins:
  - exclude:
      glob:
        - '**/_*'
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
  - redirects:
      redirect_maps:
          2/index.md: index.md
          3/configuration-changes.md: 3/breaking-changes.md
          3/index.md: index.md
          4/index.md: index.md
  - search
theme:
  name: cinder
  highlightjs: true
  disable_nav_previous_next: true
copyright: All documentation is licensed under the <a href="/license">GNU GPLv2</a>.
repo_url: https://github.com/inspircd/inspircd-docs
site_description: InspIRCd is a modular C++ Internet Relay Chat (IRC) server for UNIX-like and Windows systems.
site_name: InspIRCd Documentation
site_url: https://docs.inspircd.org/
