INHERIT: mkdocs_dev.yml

plugins:
    # Only use minify when building for prod, as it takes a relatively
    # long time to run.
    minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true

    # Don't need redirects in dev
    redirects:
      redirect_maps:
          3/configuration-changes.md: 3/breaking-changes.md
          3/index.md: index.md
          3/modes.md: 3/channel-modes.md
          4/index.md: index.md
          faq/windows.md: faq.md
          social.md: support.md
